- source/Telephony.js
Signed-off-by: Simon Busch <morphis@gravedo.de>
> Correct WAN status handling

- build-and-deploy.sh
- source/views/Certificates.js
- source/views/Settings.js
- source/views/package.js
No possible to delete certificates yet but import and viewing works.
> Certificate manager implementation

- source/views/Certificates.js
Note: I have not tested this (I don't know quite how) beyond a successful deploy and install of Settings on my N4.
> Certificates: Catch up with webos-lib and enyo-webos changes

- source/views/Certificates.js
Signed-off-by: Simon Busch <morphis@gravedo.de>
> List certificates again after adding a new one

- source/style/App.css
- source/views/DateTime.js
- source/views/Settings.js
Add UTC offsets
Tighten up layout
Use back gesture to cancel time zone change
(I'll look at City Search next)
> Time zones list improvements

- source/style/App.css
- source/views/DateTime.js
- source/views/Settings.js
This is on top of the time zones list work still available on another PR.
Filter the time zones list by typing a string in the search box I have added to the panel's header.
The search string can occur anywhere in the city name (not just at the start) and is case-insensitive.
Layout looks OK on a Nexus 4, I say.
> Time zones city search

- source/views/Telephony.js
Added lots of logging to expose what is going on.
Does it really make sense to subscribe to GetWanStatus?
(Subscribing is useful for debugging, actually.)
Where else would these settings be modified?
> Telephony: Set settings for user actions only

- source/views/SearchPreferences.js
> SearchPrefs: Without the nasty toLowerCase hack

- source/views/Bluetooth.js
- source/views/Settings.js
- source/views/WiFi.js
This might be worth having:
- as tangible evidence of progress towards proper Bluetooth functionality, and
- as a debugging tool for people who know more about the Bluetooth machinery than I do.
> Discover your devices. See interesting issues in the logs.

- source/views/Bluetooth.js
Rudimentary action on change of our own Discoverability.
Not strictly correct action, but this is how the Properties work.
> Bluetooth: Make use of a changed Property

- source/views/Bluetooth.js
A minor improvement (and not a very elegant one) but this ought to help with debugging the BluetoothManager plugin.
Adds a Connecting status message and uses the correct connection state values so you get a better idea of what is really going on.
> Bluetooth: More user feedback

- source/views/Bluetooth.js
My Bluetooth work in progress.
I'd like to get this out there so people can try to get Bluetooth connectivity to actually do useful things.
I get devices in the list and evidence of pairing / connection but not much else. The system log suggests there are things under the hood that are not right yet.
> Bluetooth useful for debugging

- source/views/Settings.js
- source/views/WiFi.js
Resolves issue #623.
I believe the code I have removed was doing work that was not necessary. This version behaves well for me.
To do:
- Provide feedback when a hidden network is not known.
- Allow Joining of visible networks as well.
> Connect to hidden WiFi networks with less code

- source/views/Bluetooth.js
Pass the key value pair, as intended.
There is a corresponding PR for luna-webappmanager.
> BlueTooth: Accept proper propertyChanged arguments

- source/views/LanguageInput.js
Avoid having to specify settings that we otherwise ignore here.
Just a suggestion.
> LanguageInput: Settings only sets what it knows about

- source/views/About.js
Resolves issue [1125](http://issues.webos-ports.org/issues/1125).
> About: Make Wi-Fi MAC address easily available

- source/views/SystemUpdates.js
Should be pulled together with these changes in update server: https://github.com/webOS-ports/org.webosports.update/pull/16
Signed-off-by: Achim Königs <garfonso@tratschtante.de>
> adjustments to new update service

- src/qml/Common/BasePage.qml
- src/qml/GenericCategoryWindow.qml
- src/qml/Testing/ExamplePage.qml
- src/qml/main.qml
> Propose an example page

- src/qml/CategoryHeader.qml
- src/qml/Connectivity/BluetoothPage.qml
- src/qml/Connectivity/WiFiPage.qml
- src/qml/GenericCategoryWindow.qml
> Some fonts and layout fixes

- src/qml/Connectivity/BluetoothPage.qml
> BluetoothPage: switch to BluezQt

- src/qml/Connectivity/BluetoothAuthorizeServicePopup.qml
- src/qml/Connectivity/BluetoothConfirmAuthorizePopup.qml
- src/qml/Connectivity/BluetoothConfirmPassKeyPopup.qml
- src/qml/Connectivity/BluetoothDisplayPassKeyPopup.qml
- src/qml/Connectivity/BluetoothDisplayPinCodePopup.qml
- src/qml/Connectivity/BluetoothPage.qml
- src/qml/Connectivity/BluetoothProvidePassKeyPopup.qml
- src/qml/Connectivity/BluetoothProvidePinCodePopup.qml
> BluetoothPage: implement pairing

- src/qml/Connectivity/WiFiPage.qml
- src/qml/Connectivity/WiFiProvidePassphrasePopup.qml
We probably need a Connman agent to complete this code.
> WifiPage: partial implementation of connection

- src/qml/Connectivity/BluetoothPage.qml
- src/qml/Connectivity/WiFiPage.qml
> WifiPage & BluetoothPage: improve aesthetics

- src/qml/General/AboutPage.qml
> AboutPage: use luna:// instead of palm://

- files/sysbus/org.webosports.app.settings.json.prv.in.in
> Fix LS2 permissions for "" service name

- data/appinfo.backup.json
- data/appinfo.certificate.json
- data/appinfo.dateandtime.json
- data/appinfo.exhibitionpreferences.json
- data/appinfo.help.json
- data/appinfo.languagepicker.json
- data/appinfo.location.json
- data/appinfo.networksettings.json
- data/appinfo.screenlock.json
- data/appinfo.searchpreferences.json
- data/appinfo.soundsandalerts.json
- data/appinfo.textassist.json
- data/appinfo.updates.json
- data/appinfo.vpn.json
- src/qml/Connectivity/BluetoothPage.qml
Signed-off-by: Herman van Hazendonk <github.com@herrie.org>
> org.webosports.app.settings-qml: Various cleanups

- src/qml/General/DeviceInfoPage.qml
Populate Version & Android Version fields with values.
Signed-off-by: Herman van Hazendonk <github.com@herrie.org>
> DeviceInfoPage.qml: Add more missing info

- source/views/Certificates.js
- source/views/Sound.js
Signed-off-by: Herman van Hazendonk <github.com@herrie.org>
> Update Certificates.js and Sound.js for updated service names

- src/qml/GenericCategoryWindow.qml
- src/qml/main.qml
> Make settings apps compatible with qml-runner

- src/qml/Connectivity/WiFiPage.qml
- src/qml/GenericCategoryWindow.qml
> Fix window not appearing on device

- data/appinfo.backup.json
- data/appinfo.bluetooth.json
- data/appinfo.certificate.json
- data/appinfo.dateandtime.json
- data/appinfo.deviceinfo.json
- data/appinfo.devmodeswitcher.json
- data/appinfo.exhibitionpreferences.json
- data/appinfo.help.json
- data/appinfo.languagepicker.json
- data/appinfo.location.json
- data/appinfo.networksettings.json
- data/appinfo.screenlock.json
- data/appinfo.searchpreferences.json
- data/appinfo.soundsandalerts.json
- data/appinfo.textassist.json
- data/appinfo.updates.json
- data/appinfo.vpn.json
- data/appinfo.wifi.json
- src/qml/Connectivity/WiFiPage.qml
- src/qml/GenericCategoryWindow.qml
Signed-off-by: Herman van Hazendonk <github.com@herrie.org>
> Migrate to Enhanced ACG and LSM
